version: 0.0
os: linux
files:
  - source: /
    destination: /opt/erp-app
hooks:
  BeforeInstall:
    - location: codedeploy/before_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: codedeploy/start_server.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: codedeploy/validate_service.sh
      timeout: 120
      runas: root
