version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
  pre_build:
    commands:
      - pytest -q
  build:
    commands:
      - echo "Build completed on $(date)"
artifacts:
  files:
    - '**/*'
